version: '3'
services:
  redis:
    image: redis:latest
    container_name: ${ICEES_API_INSTANCE_NAME}-cache
    restart: always
  server:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        UID: $UID
        GID: $GID
    image: icees-api-server:0.5.1
    container_name: ${ICEES_API_INSTANCE_NAME}-server
    env_file:
      - .env
    restart: always
    environment:
      CONFIG_PATH: /icees-api/config
      ICEES_API_LOG_PATH: /log
      ICEES_DB: sqlite
      DB_PATH: /data/example.db
      REDIS_HOST: redis
    volumes:
      - $DB_PATH:/data
      - $CONFIG_PATH:/icees-api/config
      - $ICEES_API_LOG_PATH:/log
    ports:
    - "${ICEES_API_HOST_PORT}:8080"
