version: '3'
services:
  redis:
    image: redis:latest
    container_name: ${ICEES_API_INSTANCE_NAME}-cache
  server:
    build: 
      context: .
    image: icees-api-server:0.5.0
    container_name: ${ICEES_API_INSTANCE_NAME}-server
    env_file:
      - .env
    restart: always
    environment:
      CONFIG_PATH: /icees-api/config
      ICEES_API_LOG_PATH: /log
      ICEES_HOST: db
      ICEES_DB: postgres
      REDIS_HOST: redis
    volumes:
      - $CONFIG_PATH:/icees-api/config
      - $ICEES_API_LOG_PATH:/log
    ports:
    - "${ICEES_API_HOST_PORT}:8080"
