version: '3'
services:
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    image: icees-api-db:0.2.0
#    ports:
#    - "5432:5432"
    environment:
    - ICEES_DBUSER
    - ICEES_DBPASS
    - ICEES_DATABASE
    - ICEES_DB_POOL_SIZE
    - ICEES_DB_MAX_OVERFLOW
    volumes:
      - data:/data
    restart: always
  server:
    build: 
      context: .
    image: icees-api-server:0.2.0
    environment:
    - ICEES_DBUSER
    - ICEES_DBPASS
    - ICEES_HOST
    - ICEES_PORT
    - ICEES_DATABASE
    - ICEES_API_LOG_PATH
    - ICEES_DB_POOL_SIZE
    - ICEES_DB_MAX_OVERFLOW
    restart: always
    depends_on:
      - db
    ports:
    - "${ICEES_API_HOST_PORT}:8080"

volumes:
  data:
