version: '3'
services:
  db_init:
    image: python:3.9.1-buster
    container_name: ${ICEES_API_INSTANCE_NAME}-db-initializer
    volumes:
      - $CONFIG_PATH:/config
      - ./db:/db
    env_file:
      - .env
    environment:
      ICEES_DB: sqlite
    command: "./db/initdb.sh"
  server:
    build: 
      context: .
    image: icees-api-server:0.5.0
    container_name: ${ICEES_API_INSTANCE_NAME}-server
    env_file:
      - .env
    restart: always
    environment:
      CONFIG_PATH: /icees-api/config
      ICEES_API_LOG_PATH: /log
      ICEES_HOST: db
    volumes:
      - $CONFIG_PATH:/icees-api/config
      - $ICEES_API_LOG_PATH:/log
      - ./db:/db
    ports:
    - "${ICEES_API_HOST_PORT}:8080"
