version: '3'
services:
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    image: icees-api-db:0.2.0
#    ports:
#    - "5432:5432"
    env_file:
      - .env
    volumes:
      - data:/data
    restart: always
  server:
    build: 
      context: .
    image: icees-api-server:0.2.0
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    ports:
    - "${ICEES_API_HOST_PORT}:8080"

volumes:
  data:
