version: '3'
services:
  db:
    image: postgres:12.4-alpine
    container_name: ${ICEES_API_INSTANCE_NAME}-db
    environment:
      POSTGRES_USER: ${ICEES_DBUSER}
      POSTGRES_PASSWORD: ${ICEES_DBPASS}
      POSTGRES_DB: ${ICEES_DATABASE}
    ports:
      - "5432:5432"
  db_init:
    image: python:3.9.1-buster
    container_name: ${ICEES_API_INSTANCE_NAME}-db-initializer
    volumes:
      - $CONFIG_PATH:/config
      - ./db:/db
    environment:
      ICEES_DB: postgres
      ICEES_DBUSER: ${ICEES_DBUSER}
      ICEES_DBPASS: ${ICEES_DBPASS}
      ICEES_HOST: db
      ICEES_PORT: ${ICEES_PORT}
      ICEES_DATABASE: ${ICEES_DATABASE}
      ICEES_DB_MAX_OVERFLOW: ${ICEES_DB_MAX_OVERFLOW}
      ICEES_DB_POOL_SIZE: ${ICEES_DB_POOL_SIZE}
    command: "./db/initdb.sh"
  server:
    build: 
      context: .
    image: icees-api-server:0.5.0
    container_name: ${ICEES_API_INSTANCE_NAME}-server
    env_file:
      - .env
    restart: always
    environment:
      CONFIG_PATH: /icees-api/config
      ICEES_API_LOG_PATH: /log
      ICEES_HOST: db
      ICEES_DB: postgres
    volumes:
      - $CONFIG_PATH:/icees-api/config
      - $ICEES_API_LOG_PATH:/log
    depends_on:
      - db
    ports:
    - "${ICEES_API_HOST_PORT}:8080"

