version: '3'
services:
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    image: icees-api-db:0.2.0
    container_name: ${ICEES_API_INSTANCE_NAME}-db
    env_file:
      - .env
    volumes:
      - $DB_PATH:/data
      - $DATA_PATH:/db/data
      - ./config:/icees-api/config
    restart: always
  server:
    build: 
      context: .
    image: icees-api-server:0.2.0
    container_name: ${ICEES_API_INSTANCE_NAME}-server
    env_file:
      - .env
    restart: always
    volumes:
      - ./config:/icees-api/config
    depends_on:
      - db
    ports:
    - "${ICEES_API_HOST_PORT}:8080"

