from sqlalchemy import Table, Column, Integer, String, MetaData, ForeignKey, create_engine, Boolean, func, Float, Sequence, Enum

age_bins = Enum('0-2', '3-17', '18-34', '35-50', '51-69', '70+')

features = [
    ("AgeStudyStart", age_bins),
    ("Sex", String),
    ("Race", String),
    ("Ethnicity", String),
    ("AsthmaDx", Integer),
    ("CroupDx", Integer),
    ("ReactiveAirwayDx", Integer),
    ("CoughDx", Integer),
    ("PneumoniaDx", Integer),
    ("ObesityICD", Integer),
    ("ObesityBMI", Integer),
    ("AvgDailyPM2.5Exposure", Integer),
    ("MaxDailyPM2.5Exposure", Integer),
    ("AvgDailyOzoneExposure", Integer),
    ("MaxDailyOzoneExposure", Integer),
    ("EstResidentialDensity", Integer),
    ("EstResidentialDesnity25Plus", Integer),
    ("EstProbabilityNonHispWhite", Integer),
    ("EstProbabilityHouseholdNonHispWhite", Integer),
    ("EstProbabilityHighSchoolMaxEducation", Integer),
    ("EstProbabilityNoAuto", Integer),
    ("EstProbabilityNoHealthIns", Integer),
    ("EstProbabilityESL", Integer),
    ("EstHouseholdIncome", Integer),
    ("MajorRoadwayHighwayExposure", Integer),
    ("TotalEDInpatientVisits", Integer),
    ("Prednisone", Integer),
    ("Fluticasone", Integer),
    ("Mometasone", Integer),
    ("Budesonide", Integer),
    ("Beclomethasone", Integer),
    ("Ciclesonide", Integer),
    ("Flunisolide", Integer),
    ("Albuterol", Integer),
    ("Metaproterenol", Integer),
    ("Diphenhydramine", Integer),
    ("Fexofenadine", Integer),
    ("Cetirizine", Integer),
    ("Ipratropium", Integer),
    ("Salmeterol", Integer),
    ("Arformoterol", Integer),
    ("Formoterol", Integer),
    ("Indacaterol", Integer),
    ("Theophylline", Integer),
    ("Omalizumab", Integer),
    ("Mepolizumab", Integer),
]

