apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asthma-redis-db-pvc
  namespace: icees-dev
spec:
  storageClassName: basic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

