patient:
  A*02:01:
    biolinkType: SequenceVariant
    minimum: 0
    maximum: 2
    type: integer
  A1AT_Deficiency:
    biolinkType: PhenotypicFeature, Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  ALT_DILIOnset_ULN:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    type: number
  ALT_Onset:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    type: number
  ALT_Peak_DILIOnsetToMonth6:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    type: number
  ALT_Peak_DILIOnsetToMonth6_ULN:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    type: number
  ANA:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  ASMA:
    biolinkType: PhenotypicFeature , DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  AST_DILIOnset_ULN:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    type: number
  AST_Onset:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    type: number
  AST_Peak_DILIOnsetToMonth6:
    type: number
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
  AST_Peak_DILIOnsetToMonth6_ULN:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    type: number
  AbdominalPain:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  AgeQualifyingLab:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    type: number
  AlcoholRelatedLiverDisease:
    biolinkType: Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  AlcoholUse:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  AlkalinePhosphatase_DILIOnset_ULN:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    type: number
  AlkalinePhosphatase_Onset:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    type: number
  AlkalinePhosphatase_Peak_DILIOnsetToMonth6:
    type: number
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
  AlkalinePhosphatase_Peak_DILIOnsetToMonth6_ULN:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    type: number
  AmoxicillinDILIDx:
    biolinkType: Disease, DiseaseOrPhenotypicFeature
    maximum: 1
    minimum: 0
    type: integer
  Anti_HAV:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  Anti_HBc:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  Anti_HBc_IgM:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  Anti_HBe:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  Anti_HBs:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  Anti_HCV:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  AutoimmuneHepatitis:
    biolinkType: PhenotypicFeature, Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  BMI:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    type: number
  Bilirubin_DILIOnset_ULN:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    type: number
  Bilirubin_Onset:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    type: number
  Bilirubin_Peak_DILIOnsetToMonth6:
    type: number
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
  Bilirubin_Peak_DILIOnsetToMonth6_ULN:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    type: number
  ChronicDILI:
    biolinkType: PhenotypicFeature, Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  ChronicHepatitisB_Screening:
    biolinkType: PhenotypicFeature, Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  ChronicHepatitisC_Screening:
    biolinkType: PhenotypicFeature, Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  Cirrhosis:
    biolinkType: PhenotypicFeature, Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  ConcomitantDrugs:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "0 to 2"
    - "3 to 5"
    - '>5'
    type: string
  CongestiveHeartFailure:
    biolinkType: Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  DILIDx:
    biolinkType: Disease, DiseaseOrPhenotypicFeature
    maximum: 1
    minimum: 0
    type: integer
  DILIN_SeverityScore:
    biolinkType: PhenotypicFeature, Disease, DiseaseOrPhenotypicFeature
    enum:
    - Mild
    - Moderate
    - Moderate-hospitalized
    - Severe
    - Fatal
    type: string
  DRB1*15:01:
    biolinkType: SequenceVariant
    minimum: 0
    maximum: 2
    type: integer
  Days_AlkalinePhosphatase_DILIOnsetToPeak:
    type: number
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
  Days_ALT_DILIOnsetToPeak:
    type: number
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
  Days_AST_DILIOnsetToPeak:
    type: number
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
  Days_Bilirubin_DILIOnsetToPeak:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    type: number
  Days_DILIOnsetToInitialVisit:
    biolinkType: PhenotypicFeature
    type: integer
  Days_DrugStartToEarliestSign:
    biolinkType: PhenotypicFeature
    type: integer
  Days_DrugStartToEarliestSignOrDILI:
    biolinkType: PhenotypicFeature
    type: integer
  Days_EarliestSignToDILI:
    biolinkType: PhenotypicFeature
    type: integer
  Days_EarliestSignToDrugStop:
    biolinkType: PhenotypicFeature
    type: integer
  Death:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  DiabetesEndocrineDisorder:
    biolinkType: Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  DrugAllergy:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  EosinophilCount:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    type: number
  Eosinophil_GreaterThan500:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  EthnicityDILI:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  FamilyHistoryLiverDisease:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  Fever:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  FinalCausalityScore:
    biolinkType: PhenotypicFeature, Disease, DiseaseOrPhenotypicFeature
    enum:
    - "Unlikely Less than 25%"
    - "Possible 25-50%"
    - "Probable 50-75%"
    - "Highly likely 75-95%"
    - "Definite Greater than 95%"
    type: string
  GastrointestinalDisease:
    biolinkType: Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  GilbertsSyndrome:
    biolinkType: PhenotypicFeature, Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  HBV_Positive:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  HBeAg:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  HBsAg:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  HCV_Positive:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "Yes"
    - "No"
    type: string
  HCV_RNA:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  HIV_Positive:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  HLA-B*15:18:
    biolinkType: SequenceVariant
    minimum: 0
    maximum: 2
    type: integer
  HeartDisease:
    biolinkType: Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  Hemochromatosis:
    biolinkType: PhenotypicFeature, Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  HepatitisA:
    biolinkType: PhenotypicFeature, Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  Hospitalization_NewProlonged:
    biolinkType: ActivityAndBehavior, PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  INR_Onset:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    type: number
  INR_Peak_DILIOnsetToMonth6:
    type: number
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
  Implicated_Drug1_Assessment:
    biolinkType: ChemicalSubstance, ChemicalExposure, Drug
    enum:
    - Unlikely Less than 25%
    - Possible 25-50%
    - Probable 50-75%
    - Highly likely 75-95%
    - Definite Greater than 95%
    type: string
  Implicated_Drug2_Assessment:
    biolinkType: ChemicalSubstance, ChemicalExposure, Drug
    enum:
    - Unlikely Less than 25%
    - Possible 25-50%
    - Probable 50-75%
    - Highly likely 75-95%
    - Definite Greater than 95%
    type: string
  Implicated_Drug3_Assessment:
    biolinkType: ChemicalSubstance, ChemicalExposure, Drug
    enum:
    - Unlikely Less than 25%
    - Possible 25-50%
    - Probable 50-75%
    - Highly likely 75-95%
    - Definite Greater than 95%
    type: string
  Initial_RUCAM:
    biolinkType: PhenotypicFeature, Disease, DiseaseOrPhenotypicFeature
    enum:
    - Excluded
    - Unlikely
    - Possible
    - Probable
    - Highly Probable
    type: string
  IschemicHepatitis:
    biolinkType: PhenotypicFeature, Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  Itching:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  Jaundice:
    biolinkType: PhenotypicFeature, Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  Latency:
    biolinkType: PhenotypicFeature
    type: integer
  LiverBiopsy_Screen:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  LiverRelatedDeath:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  LiverTransplant:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  Malignancy:
    biolinkType: Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  NAFLD:
    biolinkType: Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  Nausea:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  NeurologicalDisease:
    biolinkType: Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  Neutropenia:
    biolinkType: PhenotypicFeature, Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  PCA_Race:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - White
    - Black
    - East Asian
    - Hispanic
    - Other/Multiracial
    type: string
  PatternLiverInjury_Onset:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - Cholestatic
    - Hepatocellular
    - Mixed
    type: string
  PrednisoneOrCorticosteroids_Tx:
    biolinkType: ChemicalSubstance, ChemicalExposure, Drug
    enum:
    - "No"
    - "Yes"
    type: string
  PrimaryBiliaryCirrhosis:
    biolinkType: PhenotypicFeature, Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  PrimarySclerosingCholangitis:
    biolinkType: PhenotypicFeature, Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  PulmonaryDisease:
    biolinkType: Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  RValue_Onset:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    type: number
  RaceDILI:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - White or Caucasian
    - Black or African American
    - Asian
    - Other/Multiracial
    type: string
  Rash:
    biolinkType: PhenotypicFeature, DiseaseOrPhentoypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  RenalDisease:
    biolinkType: Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  Serum_IgA:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    type: number
  Serum_IgG:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    type: number
  Serum_IgM:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    type: number
  SexDILI:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - Male
    - Female
    type: string
  StevensJohnsonSyndrome:
    biolinkType: Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  Thrombocytopenia:
    biolinkType: PhenotypicFeature, Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  UnexplainedAbnormalLiverTest:
    biolinkType: PhenotypicFeature, Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  WHONAME_Implicated_Drug1:
    biolinkType: ChemicalSubstance, ChemicalExposure, Drug
    type: string
  WHONAME_Implicated_Drug2:
    biolinkType: ChemicalSubstance, ChemicalExposure, Drug
    type: string
  WHONAME_Implicated_Drug3:
    biolinkType: ChemicalSubstance, ChemicalExposure, Drug
    type: string
  Weeks_DrugStartToDILI:
    biolinkType: PhenotypicFeature
    enum:
    - <= 1 week
    - 2 to 4 weeks
    - 5 to 12 weeks
    - 13 to 24 weeks
    type: string
  Weeks_DurationOfSickness:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    enum:
    - Less than a week
    - 1 week
    - 2-4 weeks
    - More than 4 weeks
    type: string
  Weeks_EarliestSignToDILI:
    biolinkType: PhenotypicFeature
    enum:
    - <= 1 week
    - 2-4 weeks
    - "> 4 weeks"
    type: string
  Weight:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    type: number
  WilsonsDisease:
    biolinkType: Disease, DiseaseOrPhenotypicFeature
    enum:
    - "No"
    - "Yes"
    type: string
  Year_DILI_Onset:
    biolinkType: PhenotypicFeature, DiseaseOrPhenotypicFeature
    type: string
#    maximum: 2050
#    minimum: 1900
#    type: integer
  rs1363907_a:
    biolinkType: SequenceVariant
    minimum: 0
    maximum: 2
    type: integer
  rs2476601_a:
    biolinkType: SequenceVariant
    minimum: 0
    maximum: 2
    type: integer
