apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: server-covid-dev
  name: server-covid-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server-covid-dev
  strategy:
    type: Recreate      
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.25.0 (a70f80cc)
      creationTimestamp: null
      labels:
        io.kompose.service: server-covid-dev
    spec:
      containers:
        - image: renci/icees-api-server:0.5.0
          name: trapi-v1-covid-dev-server
          ports:
            - containerPort: 8080
          env:
           - name: UID
             value: "1001"
           - name: GID
             value: "1001"  
           - name: ICEES_PORT
             value: "5432"
           - name: ICEES_HOST
             valueFrom:
               secretKeyRef:
                 name: covid-config
                 key: ICEES_HOST       
           - name: ICEES_DBUSER 
             valueFrom:
               secretKeyRef:
                 name: covid-config
                 key: ICEES_DBUSER
           - name: ICEES_DBPASS
             valueFrom:
               secretKeyRef:      
                 name: covid-config
                 key: ICEES_DBPASS
           - name: POSTGRES_PASSWORD 
             valueFrom:
               secretKeyRef:      
                 name: covid-config
                 key: POSTGRES_PASSWORD
           - name: ICEES_DATABASE
             valueFrom:
               secretKeyRef:      
                 name: covid-config
                 key: ICEES_DATABASE
           - name: ICEES_API_LOG_PATH
             value: "/iceesdata/covid/logs"
           - name: ICEES_API_HOST_PORT
             value: "8080"
           - name: POOL_SIZE
             value: "10"
           - name: MAX_OVERFLOW
             value: "0"
           - name: OPENAPI_TITLE 
             value: "ICEES COVID Instance API"
           - name: OPENAPI_HOST
             value: "icees-covid-dev.apps.renci.org"
           - name: OPENAPI_SCHEME
             value: "https"
           - name: DATA_PATH
             value: "./db/data"
           - name: DB_PATH
             value: "/iceesdata/covid/sqlite/example.db"
           - name: CONFIG_PATH 
             value: "/iceesdata/covid/config"
           - name: ICEES_API_INSTANCE_NAME
             value: "trapi-v1.2-covid-dev"
           - name: OPENAPI_SERVER_URL
             value: "https://icees-covid-dev.apps.renci.org"
           - name: ICEES_INFORES_CURIE 
             value: "infores:icees-covid"
           - name: OPENAPI_SERVER_MATURITY
             value: "development"
           - name: OPENAPI_SERVER_LOCATION
             value: "RENCI"
           - name: REDIS_HOST
             value: "redis-covid-dev"  
          livenessProbe:
            periodSeconds: 5
            httpGet:
              path: /apidocs
              port: 8080   
          startupProbe:
            httpGet:
              path: /apidocs
              port: 8080
            failureThreshold: 30
            periodSeconds: 5 
          readinessProbe:
            periodSeconds: 5
            httpGet:
              path: /apidocs
              port: 8080    
          volumeMounts:
            - name: iceesdata          
              mountPath: /iceesdata
          resources: 
            requests: 
              cpu: "1"
              memory: 8Gi    
            limits:
              memory: "10Gi"
              cpu: "2"   
              
      restartPolicy: Always
      volumes:
        - name: iceesdata
          persistentVolumeClaim:
            claimName: iceesdata
